nohup python main.py ./configs/config_ema_ssim_twd_exp_mean_new_models_60.ini > logs_ensemble_ssim_twd_exp_mean_new_models_60.out
wait
nohup python main.py ./configs/config_ema_ssim_twd_exp_mean_with_rgb_new_models_60.ini > logs_ensemble_ssim_twd_exp_mean_with_rgb_new_models_60.out
wait 
nohup python main.py ./configs/config_ema_ssim_twd_exp_median_faster_new_models_60.ini > logs_ensemble_ssim_twd_exp_median_faster_new_models_60.out
wait 
nohup python main.py ./configs/config_ema_ssim_twd_exp_median_faster_with_rgb_new_models_60.ini > logs_ensemble_ssim_twd_exp_median_faster_with_rgb_new_models_60.out
wait
nohup python main.py ./configs/config_ema_ssim_twd_exp_median_new_models_60.ini > logs_ensemble_ssim_twd_exp_median_new_models_60.out
wait
nohup python main.py ./configs/config_ema_ssim_twd_exp_median_with_rgb_new_models_60.ini > logs_ensemble_ssim_twd_exp_median_with_rgb_new_models_60.out
wait
